### ISSUE TITLE
Add .gitignore for Python

### ISSUE THREAD

**Issue by oberbichler** [KlausBSautter/PythonTOP#2]
Hi!
I suggest to add a `.gitignore` file for Python. That should make `sys.dont_write_bytecode = True` at the beginning of each script obsolete.

You can see my changes in the [feature/gitignore](https://github.com/KlausBSautter/PythonTOP/tree/feature/gitignore) branch.

**Comment by KlausBSautter** [comment]
Thanks @oberbichler . I just merged your changes in the master
