### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by armingeiser** [KlausBSautter/PythonTOP#6]
It appears that we have problems with merging when we change the folder structure while others are working on files that are affected by those changes...

Therefore i suggest that we do such kind of restructuring only after announcements.

This saves us a lot of work.

**Comment by oberbichler** [comment]
master-branch = official folder structure?

**Comment by armingeiser** [comment]
for now ;-)
even if i would suggest to put the gui_functions in a "GUI" folder, and only keep a single main script at the top directory

**Comment by KlausBSautter** [comment]
I think this issue is solved with the latest update
