### ISSUE TITLE
Add a run script

### ISSUE THREAD

**Issue by oberbichler** [KlausBSautter/PythonTOP#7]
Adding a simple `run.cmd` in the root folder with the single line

```
python gui_top/top_main_gui.py
```

would make it possible to start the GUI with a double-click.

**Comment by oberbichler** [comment]
![run](https://user-images.githubusercontent.com/7000594/31234262-becf444c-a9ee-11e7-9188-e77deb230cc9.gif)

**Comment by armingeiser** [comment]
In principle yes, but only if python is accessible by "python" which is not the case for my machine e.g. or in the cip-pool...

**Comment by oberbichler** [comment]
Yes that is a problem. Specially the cip-pool. How do you call python there?

**Comment by armingeiser** [comment]
I don't know it by heart, but anyway, for the students it would be also ok to have a simple python script, similar to the existing top_main_gui.py, just without the tkinter stuff.
